version: 2
jobs:
  build-deploy:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Install aws cli
          command: |
            sudo apt install python-pip python-dev
            sudo pip install awscli
            aws --version
      - checkout
      - restore_cache:
          key: node-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run build
      - deploy:
          name: Deploy to S3 if branch is Master
          command: aws s3 sync dist s3://demo.woosmap.com/storelocator/ --region eu-central-1 --acl public-read

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy:
          filters:
            branches:
              only: master







